version: '3.8'

services:
  php:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./PHP:/var/www/html  # Make sure PHP is in the correct directory
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: PROJECT
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
